# 1.获取数据
# 2.数据基本处理
## 2.1数据分割
# 3. 特征工程 - 标准化
# 4. 机器学习--线性回归
# 5. 模型评估


In [21]:
#encoding:utf-8

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


In [22]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [23]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [24]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [25]:
x_train,x_test, y_train,y_test = train_test_split(data, target, test_size=0.2)

In [26]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.fit_transform(x_test)

In [27]:
from sklearn.linear_model import SGDRegressor

In [28]:
# estimator = SGDRegressor(max_iter=1000, learning_rate='constant', eta0=0.1)
estimator = SGDRegressor()

In [29]:
estimator.fit(x_train, y_train)

SGDRegressor()

In [30]:
estimator.intercept_

array([22.5000693])

In [31]:
estimator.coef_

array([-0.80595805,  0.97956634, -0.14020969,  0.73121336, -1.93783169,
        2.78236286, -0.27378146, -3.06938459,  1.74759513, -1.20739244,
       -1.93494417,  0.77649589, -3.45822449])

In [32]:
 y_pre = estimator.predict(x_test)
print('ypre:', y_pre)
#5.2均方误差
error = mean_squared_error(y_test, y_pre)
print("error:", error)

ypre: [22.0202763   8.72873851 13.58232163 20.73646279 15.57357774 26.22945313
 19.78159106 15.91844188 22.85244406 13.59746155 11.45245114 18.14636938
 25.38928444 13.07075539 26.74643604  6.98763908 31.68494517 17.07045649
 22.411109   31.64673395 30.4995951  14.16194958 29.73192521 12.72840685
 17.5718752  17.1148579  34.95276663 19.04206006 20.27310335 36.76203258
 38.34736283 21.37816233 28.82509227 17.03545601 27.4423768  33.63012105
 23.99346622 27.64311983  5.58995645 17.64803981 22.09389636 22.09472576
 25.46927104 35.35353972 25.17962256 13.93062196  9.5826886  23.56375912
 32.74940965 15.65236313 35.45833425 10.99490181 21.31464244 33.04536973
 15.4144514  18.67628408 21.32237599 15.01599364 27.48270306 35.79503978
 18.5465034  17.73934053 17.78579241 23.14231876 22.66439723 26.92169153
 25.36586566 38.14408347 16.35082862 13.4952223  35.71632242 14.82089725
 24.37043988 23.3720686  22.01908716 20.94676327 33.12643018 21.74096346
 31.08939096 19.33443119 27.48323191 17.73428