In [1]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]

669 µs ± 8.36 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
22.3 ms ± 310 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
data = np.array([[1,2,3,4],[5,6,7,8]])
data * 10
data + data

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [19]:
data.ndim

2

In [17]:
data.shape 

(2, 4)

In [18]:

data.dtype

dtype('int64')

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
#使用numpy.empty创建全0数组的做法并不妥当
np.empty((3,3)) 

array([[ 6.17779239e-31, -1.23555848e-30,  3.08889620e-31],
       [-1.23555848e-30,  2.68733969e-30, -8.34001973e-31],
       [ 3.08889620e-31, -8.34001973e-31,  4.78778910e-31]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
float_arr = data.astype(np.float64)

print(float_arr)

float_arr.astype(np.int64)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
a=['a',4]
a

['a', 4]

In [45]:
arr = np.arange(10)
arr_slice=arr[5:8]
arr_slice


array([5, 6, 7])

In [46]:
arr_slice[1]=1234
arr_slice
arr

array([   0,    1,    2,    3,    4,    5, 1234,    7,    8,    9])

In [51]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0,2])


[7 8 9]
3
3


In [53]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [56]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [58]:
arr[[1,5,7,2],[0,3,1,2]]=0

arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [59]:
arr.T

array([[ 0,  0,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25,  0],
       [ 2,  6,  0, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19,  0, 27, 31]])

In [64]:
arr.reshape((2,16)).T

array([[ 0, 16],
       [ 1, 17],
       [ 2, 18],
       [ 3, 19],
       [ 0, 20],
       [ 5, 21],
       [ 6, 22],
       [ 7,  0],
       [ 8, 24],
       [ 9, 25],
       [ 0, 26],
       [11, 27],
       [12, 28],
       [13,  0],
       [14, 30],
       [15, 31]])

In [66]:
a1 = np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]])
a1

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [71]:
np.dot(a1.T,a1)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [73]:
a1.T @ a1

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [86]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.81969116, -1.01132332, -0.39632565,  0.3103376 ],
       [-1.19546233, -1.03739449,  0.4217547 , -0.4419148 ],
       [-0.76912214,  2.06718794,  0.85096432,  1.1849659 ],
       [ 0.56080241,  0.89764107, -0.46016327,  1.57289043]])

In [100]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((5,6))
np.random.shuffle(data) 
data

array([[ 0.57585751,  1.39897899,  1.32229806, -0.29969852,  0.90291934,
        -1.62158273],
       [-0.75938718,  0.90219827, -0.46695317, -0.06068952,  0.78884434,
        -1.25666813],
       [-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
         0.96849691],
       [-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
        -0.74088465],
       [-0.15818926,  0.44948393, -1.34360107, -0.08168759,  1.72473993,
         2.61815943]])